name: CI_build

on: [push, pull_request, workflow_dispatch]

jobs:
  validate:
    runs-on: windows-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install python modules
      working-directory: .
      run: python -m pip install -r requirements.txt

    - name: Validate folders of XML types (UDLs, autoCompletion, functionList)
      working-directory: .
      run: python .validators\validator_xml.py

    - name: Validate json and rebuild udl-list.md
      working-directory: .
      run: python .validators\validator_json.py

    - name: Rebuild Markdown
      uses: stefanzweifel/git-auto-commit-action@v5
      if: contains('push workflow_dispatch', github.event_name)
      with:
        commit_message: Automatically re-build udl-list.md

  unitTest:
    runs-on: windows-latest
    needs: validate
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Install Notepad++
      uses: crazy-max/ghaction-chocolatey@v3
      with:
        args: install -y notepadplusplus
    - name: Run FunctionList Unit Tests
      working-directory: .\Test
      run: |
        $PowerEditorSource = "C:\Program Files\Notepad++\"
        $PowerEditorLocal = ".\PowerEditor"
        Copy-Item "$PowerEditorSource" -Destination "$PowerEditorLocal\bin" -Recurse -Force
        New-Item "$PowerEditorLocal\bin\doLocalConf.xml" > $nul
        New-Item "$PowerEditorLocal\bin\userDefineLangs" -ItemType Directory -ea 0 > $nul
        python doUnitTests.py $PowerEditorLocal\bin
