name: CI_build

on: [push, pull_request, workflow_dispatch]

jobs:
  build:

    runs-on: windows-2022

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install python modules
      working-directory: .
      run: python -m pip install -r requirements.txt

    - name: Validate folders of XML types (UDLs, autoCompletion, functionList)
      working-directory: .
      run: python .validators\validator_xml.py

    - name: Validate json and rebuild udl-list.md
      working-directory: .
      run: python .validators\validator_json.py

    - uses: stefanzweifel/git-auto-commit-action@v5
      if: contains('push workflow_dispatch', github.event_name)
      with:
        commit_message: Automatically re-build udl-list.md

    #- name: Archive artifacts udl markdown
    #  uses: actions/upload-artifact@v3
    #  with:
    #      name: markdown_udl_list
    #      path: udl-list.md

