name: CI_build

on: [push, pull_request]

jobs:
  build:

    runs-on: windows-2022

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install python modules
      working-directory: .
      run: python -m pip install -r requirements.txt

    - name: Validate xml of UDLs and autoCompletions folders
      working-directory: .
      run: python .validators\validator_xml.py

    - name: Validate json
      working-directory: .
      run: python .validators\validator_json.py

    - name: Archive artifacts udl markdown
      uses: actions/upload-artifact@v3
      with:
          name: markdown_udl_list
          path: udl-list.md

